### ISSUE TITLE
Request - Armor upgrades and allowed downgrades

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ellpeck/ToolHeadSwapper#1]
I was wondering if I could ask you to add the ability to downgrade and upgrade tools or whateves. Also I would love if this could apply to gear as well!

**Comment by Ellpeck** [comment]
What do you mean by "downgrade and upgrade tools"? I mean, upgrading.. is the whole mod.
And why would you want to downgrade?

**Comment by P3rf3ctXZer0** [comment]
To recover durability ... you see I love terraria but hate the 2d ... I want tools like terraria. That you make once and they don't break ... can you make a mod that makes all tools armor etc last forever? Maybe something called "Infinium" I wish there was a command that prevented tool durability loss. I have a pokecube server.

**Comment by Ellpeck** [comment]
No, I don't want to do this as it's cheaty and I think not very logical, sorry.
